"""More changes to the schemas to match 1:1 the messages sent by the API

Revision ID: 0093dfaeb2be
Revises: e7d3ce8d461a
Create Date: 2025-01-23 12:31:52.530151+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0093dfaeb2be'
down_revision = 'e7d3ce8d461a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_messages', sa.Column('bids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('book_messages', sa.Column('asks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('book_messages', 'sells')
    op.drop_column('book_messages', 'buys')
    op.add_column('price_change_messages', sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('price_change_messages', 'size')
    op.drop_column('price_change_messages', 'price')
    op.drop_column('price_change_messages', 'side')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_change_messages', sa.Column('side', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('price_change_messages', sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('price_change_messages', sa.Column('size', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('price_change_messages', 'changes')
    op.add_column('book_messages', sa.Column('buys', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('book_messages', sa.Column('sells', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('book_messages', 'asks')
    op.drop_column('book_messages', 'bids')
    # ### end Alembic commands ### 