"""Removing the 'clob_token_id' from the tables corresponding the the websocket messages, as these are instead contained in the asset_id of the raw messages (just a name change)

Revision ID: e7d3ce8d461a
Revises: fdf5a539e65a
Create Date: 2025-01-21 19:45:20.114034+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d3ce8d461a'
down_revision = 'fdf5a539e65a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_messages_clob_token_id', table_name='book_messages')
    op.create_index(op.f('ix_book_messages_asset_id'), 'book_messages', ['asset_id'], unique=False)
    op.drop_constraint('book_messages_clob_token_id_fkey', 'book_messages', type_='foreignkey')
    op.create_foreign_key(None, 'book_messages', 'outcomes', ['asset_id'], ['clob_token_id'])
    op.drop_column('book_messages', 'clob_token_id')
    op.drop_index('ix_price_change_messages_clob_token_id', table_name='price_change_messages')
    op.create_index(op.f('ix_price_change_messages_asset_id'), 'price_change_messages', ['asset_id'], unique=False)
    op.drop_constraint('price_change_messages_clob_token_id_fkey', 'price_change_messages', type_='foreignkey')
    op.create_foreign_key(None, 'price_change_messages', 'outcomes', ['asset_id'], ['clob_token_id'])
    op.drop_column('price_change_messages', 'clob_token_id')
    op.drop_index('ix_tick_size_change_messages_clob_token_id', table_name='tick_size_change_messages')
    op.create_index(op.f('ix_tick_size_change_messages_asset_id'), 'tick_size_change_messages', ['asset_id'], unique=False)
    op.drop_constraint('tick_size_change_messages_clob_token_id_fkey', 'tick_size_change_messages', type_='foreignkey')
    op.create_foreign_key(None, 'tick_size_change_messages', 'outcomes', ['asset_id'], ['clob_token_id'])
    op.drop_column('tick_size_change_messages', 'clob_token_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tick_size_change_messages', sa.Column('clob_token_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tick_size_change_messages', type_='foreignkey')
    op.create_foreign_key('tick_size_change_messages_clob_token_id_fkey', 'tick_size_change_messages', 'outcomes', ['clob_token_id'], ['clob_token_id'])
    op.drop_index(op.f('ix_tick_size_change_messages_asset_id'), table_name='tick_size_change_messages')
    op.create_index('ix_tick_size_change_messages_clob_token_id', 'tick_size_change_messages', ['clob_token_id'], unique=False)
    op.add_column('price_change_messages', sa.Column('clob_token_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'price_change_messages', type_='foreignkey')
    op.create_foreign_key('price_change_messages_clob_token_id_fkey', 'price_change_messages', 'outcomes', ['clob_token_id'], ['clob_token_id'])
    op.drop_index(op.f('ix_price_change_messages_asset_id'), table_name='price_change_messages')
    op.create_index('ix_price_change_messages_clob_token_id', 'price_change_messages', ['clob_token_id'], unique=False)
    op.add_column('book_messages', sa.Column('clob_token_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'book_messages', type_='foreignkey')
    op.create_foreign_key('book_messages_clob_token_id_fkey', 'book_messages', 'outcomes', ['clob_token_id'], ['clob_token_id'])
    op.drop_index(op.f('ix_book_messages_asset_id'), table_name='book_messages')
    op.create_index('ix_book_messages_clob_token_id', 'book_messages', ['clob_token_id'], unique=False)
    # ### end Alembic commands ### 