"""update outcome schema

Revision ID: 592202b351be
Revises: 5e83d18edd40
Create Date: 2025-01-11 17:53:49.603701+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592202b351be'
down_revision = '5e83d18edd40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcomes', 'outcome_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcomes', sa.Column('outcome_price', sa.NUMERIC(), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 